plugins {
    id 'java'
}

group = 'ru.netology'
version = '1.0-SNAPSHOT'

sourceCompatibility = 11
targetCompatibility = 11

compileJava.options.encoding = 'UTF-8'
compileTestJava.options.encoding = 'UTF-8'

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testImplementation 'com.codeborne:selenide:6.19.1'
    testImplementation 'commons-dbutils:commons-dbutils:1.8.1'
    testImplementation 'mysql:mysql-connector-java:8.0.33'
    testImplementation 'com.github.javafaker:javafaker:1.0.2'
    testCompileOnly 'org.projectlombok:lombok:1.18.30'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.30'
}

test {
    useJUnitPlatform()
    systemProperties(System.getProperties())
    systemProperty 'chromeoptions.prefs',
            System.getProperty('chromeoptions.prefs', "profile.password_manager_leak_detection=false")
}